### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by micr0dust** [micr0dust/delivery-service#16]
## feature
- [ ] coupon and sale
- [x] store area
- [x] time estimates

## member

- [x] member order post
- [x] member order preview
- [x] member account delete
- [x] get order history

## store

- [x] store refresh-token
- [x] store access-token
- [x] store update (need admin)
- [x] store delete with product delete
- [x] store get order
- [x] store finish or deny order

## product

- [ ] product update (need admin)
- [x] product delete (need admin)
- [ ] product sell pause

## website

- [ ] mail verify without access-token
- [x] store login
- [x] store console

## other plans

- [ ] cookies?
- [x] third-part login?
- [ ] image upload?
- [x] phone verify?
- [ ] 發文功能?
- [ ] 商品、商家內嵌文章功能?
- [ ] 外送員?
- [ ] 串金流?
- [ ] DDOS protect?
- [ ] CSRF protect
- [ ] hcaptcha
- [x] request rate limit
